### ISSUE TITLE
線形代数学履修取り消し

### ISSUE THREAD

**Issue by noko1024** [noko1024/human-life#4]

**Comment by Tomopu** [comment]
線形代数の後半の数ベクトル空間という概念が、代数学の群環体などに強く結びつく(実際は群環体が数ベクトル空間を作ってるけど...)ので、個人的には履修取り消ししたとしても、通年で受講してほしいなぁと思ってみたり

代数学に魅力を感じないのであれば、前提が崩れるから意味ないんだけどね。(何気にissues使うの初めてです)

**Comment by noko1024** [comment]
@Tomopu 
こっち優先して他落としたら元も子もないのと
担当教員からやめろと言われているなら取り消しちゃおうって感じです

せっかく教科書も買ってるので機会があれば教えてください！

**Comment by noko1024** [comment]
提出した！
